# Generated by Django 5.2.16 on 2026-07-13 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('employee_status', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_type', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_classification_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('termination_type', models.CharField(blank=True, max_length=100, null=True)),
                ('termination_description', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('location_code', models.CharField(blank=True, max_length=100, null=True)),
                ('gender_code', models.CharField(blank=True, max_length=20, null=True)),
                ('race_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('readiness_score', models.FloatField(default=0.0)),
                ('performance_score', models.CharField(blank=True, max_length=100, null=True)),
                ('current_employee_rating', models.IntegerField(blank=True, null=True)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('engagement_score', models.FloatField(blank=True, null=True)),
                ('satisfaction_score', models.FloatField(blank=True, null=True)),
                ('work_life_balance_score', models.FloatField(blank=True, null=True)),
                ('training_date', models.DateField(blank=True, null=True)),
                ('training_program_name', models.CharField(blank=True, max_length=255, null=True)),
                ('training_type', models.CharField(blank=True, max_length=100, null=True)),
                ('training_outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('trainer', models.CharField(blank=True, max_length=255, null=True)),
                ('training_duration_days', models.IntegerField(blank=True, null=True)),
                ('training_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='professionals.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proficiency', models.CharField(blank=True, max_length=50, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='professionals.professional')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.skill')),
            ],
        ),
    ]
